/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaaer;

import DAO.ContratacionesDAO;
import DAO.ReporteDao;
import DAO.usuarioDao;
import Modelo.InnerContratacion;
import Modelo.InnerUsuario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author javam
 */
public class frmBusquedaListaContratacion extends javax.swing.JFrame {

    /**
     * Creates new form frmBusquedaListaCliente
     */
    private ArrayList<InnerContratacion> lstModContra;
    private final ContratacionesDAO contraDao = new ContratacionesDAO();
    private final InnerContratacion modInnerEmp = new InnerContratacion();
    private DefaultTableModel tblModelContra;
 
    public frmBusquedaListaContratacion() {
        initComponents();
        llenarTabla();
    }

//    private void limpiar() {
//        if (tblModelCliente.getRowCount() != 0) {
//
//            for (int i = 0; i < tblModelCliente.getRowCount(); i++) {
//                tblModelCliente.removeRow(0);
//            }
//        }
//    }
    private void limpiarOtraForma(){
        while(tblModelContra.getRowCount()>0){
            tblModelContra.removeRow(0);
        }
    }
    private void llenarTabla() {
        tblModelContra = (DefaultTableModel) tblContrato.getModel();
        Object[] column = new Object[tblModelContra.getColumnCount()];
        
        try {
            lstModContra = contraDao.listarTodaContratacion();
            int tamano = lstModContra.size();

            for (int i = 0; i < tamano; i++) {
                column[0] = lstModContra.get(i).getIdContratacion();
                column[1] = lstModContra.get(i).getPaquete();
                column[2] = lstModContra.get(i).getFechaContratacion();
                column[3] = lstModContra.get(i).getFechaCulminacion();
                column[4] = lstModContra.get(i).getFechaRenovacion();
                column[5] = lstModContra.get(i).getCliente();
                column[6] = lstModContra.get(i).getDireccion();
                column[7] = lstModContra.get(i).getMunicipio();
                column[8] = lstModContra.get(i).getIdEmpleado();
                tblModelContra.addRow(column);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloElCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContrato = new javax.swing.JTable();
        btnListarImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtIdEmpleado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloElCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblTituloElCliente.setText("Lista de Contratos Existentes");
        jPanel1.add(lblTituloElCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 60));

        tblContrato.setForeground(new java.awt.Color(153, 153, 153));
        tblContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Contrato", "Paquete", "Fecha de Contratacion", "Fecha de Renovacion", "Fecha de Columinacion", "Cliente", "Direccion", "Municipio", "ID Empleado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContrato.setGridColor(new java.awt.Color(255, 255, 255));
        tblContrato.setRowHeight(25);
        tblContrato.setSelectionBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setViewportView(tblContrato);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 970, 350));

        btnListarImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btnListarImprimir.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnListarImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/printer.png"))); // NOI18N
        btnListarImprimir.setText("Listar e Imprimar");
        btnListarImprimir.setBorder(null);
        btnListarImprimir.setBorderPainted(false);
        btnListarImprimir.setContentAreaFilled(false);
        btnListarImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnListarImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnListarImprimir.setIconTextGap(10);
        btnListarImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Contrato:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 40));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/magnifying-glass.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 60, 40));
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarImprimirActionPerformed
        limpiarOtraForma();
        llenarTabla();
        
        int res = JOptionPane.showConfirmDialog(this, "¿Desea imprimir el listado de Clientes?", "Confirmacion", JOptionPane.YES_OPTION);
        if (res == 0) {
            try {
                ReporteDao rep = new ReporteDao();
                rep.generarReporteContrato();
            } catch (Exception ex) {
                Logger.getLogger(frmBusquedaListaContratacion.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
                    
        }
    }//GEN-LAST:event_btnListarImprimirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        tblModelContra = (DefaultTableModel) tblContrato.getModel();
        Object[] column = new Object[tblModelContra.getColumnCount()];
        
        modInnerEmp.setIdContratacion(Integer.parseInt(txtIdEmpleado.getText()));
        limpiarOtraForma();
        try {
//            lstModUsuario = usuDao.listarUsuarioPorId(modInnerEmp);
            
            int tamano = lstModContra.size();
            for (int i = 0; i < tamano; i++) {
                column[0] = lstModContra.get(i).getIdContratacion();
                column[1] = lstModContra.get(i).getPaquete();
                column[2] = lstModContra.get(i).getFechaContratacion();
                column[3] = lstModContra.get(i).getFechaCulminacion();
                column[4] = lstModContra.get(i).getFechaRenovacion();
                column[5] = lstModContra.get(i).getCliente();
                column[6] = lstModContra.get(i).getDireccion();
                column[7] = lstModContra.get(i).getMunicipio();
                column[8] = lstModContra.get(i).getIdEmpleado();
                tblModelContra.addRow(column);
            }
        } catch (Exception e) {
            System.err.println("Error al buscar: " + e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaListaContratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaListaContratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaListaContratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaListaContratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBusquedaListaContratacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListarImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloElCliente;
    private javax.swing.JTable tblContrato;
    private javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
