/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaaer;

import DAO.CategoriaDao;
import DAO.ClienteDao;
import DAO.EstadoDao;
import Modelo.Categoria;
import Modelo.Estado;
import Modelo.TipoClientes;
import Modelo.cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Walter
 */
public class frmModificarCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmModificarCliente
     */
    private ClienteDao clieDao = new ClienteDao();
    private cliente modCliente = new cliente();
    private ArrayList<Categoria> lstModCategoria = new ArrayList();
    private ArrayList<Estado> lstModEstado = new ArrayList();
    private ArrayList<TipoClientes> lstModTipoCliente = new ArrayList();
    public frmModificarCliente() {
        initComponents();
        listaCategoria();
        listarEstado();
        listarTipoCliente();
    }
    private void listaCategoria (){
        cboIdCategoria.removeAllItems();
        CategoriaDao catDao = new CategoriaDao();
        try {
            lstModCategoria = catDao.listarCategoria();
            for (int i = 0; i < lstModCategoria.size(); i++) {
                cboIdCategoria.addItem(lstModCategoria.get(i).getNombre());
            }
        } catch (Exception e) {
            System.err.println("Error al listar categoria: "+e);
        }
    }
    private void listarEstado(){
        cboIdEstado.removeAllItems();
        EstadoDao estDao = new EstadoDao();
        try {
            lstModEstado=estDao.listarEstado();
            for (int i = 0; i < lstModEstado.size(); i++) {
                cboIdEstado.addItem(lstModEstado.get(i).getNombre());
            }
        } catch (Exception e) {
            System.out.println("Error al listar estado: "+e);
        }
    }
    private void listarTipoCliente(){
        cboIdTipoCliente.removeAllItems();;
        lstModTipoCliente=clieDao.listarTipoCliente();
        for (int i = 0; i < lstModTipoCliente.size(); i++) {
            cboIdTipoCliente.addItem(lstModTipoCliente.get(i).getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloElCliente = new javax.swing.JLabel();
        txtIdCliente = new principal.MaterialTextField();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new principal.MaterialButton();
        lblIdEstado = new javax.swing.JLabel();
        cboIdEstado = new javax.swing.JComboBox<>();
        cboIdTipoCliente = new javax.swing.JComboBox<>();
        lblIdTipoCliente = new javax.swing.JLabel();
        lblIdCategoria = new javax.swing.JLabel();
        cboIdCategoria = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new principal.MaterialTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloElCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblTituloElCliente.setText("Modificar Cliente");
        jPanel1.add(lblTituloElCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 60));
        jPanel1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, 40));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 107, 40));

        lblIdEstado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblIdEstado.setText("Estado:");
        jPanel1.add(lblIdEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 70, 40));

        cboIdEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboIdEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, 39));

        cboIdTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboIdTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, 39));

        lblIdTipoCliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblIdTipoCliente.setText("Tipo de Cliente:");
        jPanel1.add(lblIdTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 40));

        lblIdCategoria.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblIdCategoria.setText("Categoria:");
        jPanel1.add(lblIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 70, 40));

        cboIdCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 200, 39));

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblEmail.setText("Correo Electronico:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 120, 40));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            int res = JOptionPane.showConfirmDialog(this, "¿Seguro quiere modificar los datos del cliente?","Confirmacion",JOptionPane.YES_OPTION);
            for (int i = 0; i < lstModCategoria.size(); i++) {
                if (lstModCategoria.get(i).getNombre().equals(cboIdCategoria.getSelectedItem())) {
                    int idCategoria = lstModCategoria.get(i).getId_categoria();
                    modCliente.setId_categoria(idCategoria);
                }
            }
            for (int i = 0; i < lstModEstado.size(); i++) {
                if (lstModEstado.get(i).getNombre().equals(cboIdEstado.getSelectedItem())) {
                    int idEstado = lstModEstado.get(i).getId_estado();
                    modCliente.setId_estado(idEstado);
                }
            }
            for (int i = 0; i < lstModTipoCliente.size(); i++) {
                if (lstModTipoCliente.get(i).getNombre().equals(cboIdTipoCliente.getSelectedItem())) {
                    int idTipoCliente = lstModTipoCliente.get(i).getTipoClientes();
                    modCliente.setId_tipocliente(idTipoCliente);
                }
            }
            modCliente.setEmail(txtEmail.getText());
            modCliente.setId_cliente(Integer.valueOf(txtIdCliente.getText()));
            if (res ==0) {
                clieDao.modificar(modCliente);
                JOptionPane.showMessageDialog(null, "¡Modificacion con exito!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la operacion");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModificarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnModificar;
    private javax.swing.JComboBox<String> cboIdCategoria;
    private javax.swing.JComboBox<String> cboIdEstado;
    private javax.swing.JComboBox<String> cboIdTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdCategoria;
    private javax.swing.JLabel lblIdEstado;
    private javax.swing.JLabel lblIdTipoCliente;
    private javax.swing.JLabel lblTituloElCliente;
    private principal.MaterialTextField txtEmail;
    private principal.MaterialTextField txtIdCliente;
    // End of variables declaration//GEN-END:variables
}
